# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using + and -
bind + split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# default statusbar colors
set-option -g status-bg default
set-option -g status-fg colour240

# default window title colors
set-window-option -g window-status-style fg=magenta
set-window-option -g window-status-style bg=default
set -g status-style bg=colour163
set -g status-style bg=default

set -g status-left-length 85
set -g window-status-current-format "#[fg=black,bold bg=default]_#[fg=colour135 bg=colour234]#W#[fg=black,bold bg=default]_"
set -g window-status-format "#W"
set -g status-right "#[fg=magenta] #[bg=gray] %b %d %Y %H:%M"
set -g status-justify centre


# active window title colors
set-window-option -g window-status-current-style fg=cyan
set-window-option -g window-status-current-style bg=default
