import = ["~/.config/alacritty/aura.toml"]

[cursor]
blink_interval = 550
unfocused_hollow = true
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 11.20

builtin_box_drawing = true

normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8

[keyboard]
bindings = [
  { key = "Y", mods = "Alt", action = "Copy" },
  { key = "P", mods = "Alt", action = "Paste" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
