import = ["~/.config/alacritty/aura.toml"]
[font.normal]
family = "MesloLGS NF"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8

[keyboard]
bindings = [
  { key = "Y", mods = "Alt", action = "Copy" },
  { key = "P", mods = "Alt", action = "Paste" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
