[colors.primary]
foreground = "#e4e4ef"
background = "#181818"
dim_foreground = "#5f627f"
bright_foreground = "#ffffff"

[colors.normal]
black = "#000000"
red = "#f43841"
green = "#73c936"
yellow = "#ffdd33"
blue = "#5f627f"
magenta = "#9e95c7"
cyan = "#5f627f"
white = "#ffffff"

[colors.bright]
black = "#282828"
red = "#ff4f58"
green = "#73c936"
yellow = "#ffdd33"
blue = "#96a6c8"
magenta = "#9e95c7"
cyan = "#96a6c8"
white = "#ffffff"
